from collections import OrderedDict

election_types = OrderedDict([
    ('election-G', 'General election'),
    ('election-P', 'Primary election'),
    ('election-SG', 'Special election'),
])

deadline_types = OrderedDict([
    ('report-12G', 'Pre-election'),
    ('report-30G', 'Post-election'),
    ('report-Q1', 'April quarterly'),
    ('report-Q2', 'July quarterly'),
    ('report-Q3', 'October quarterly'),
    ('report-M2', 'February monthly'),
    ('report-M3', 'March monthly'),
    ('report-M4', 'April monthly'),
    ('report-M5', 'May monthly'),
    ('report-M6', 'June monthly'),
    ('report-M7', 'July monthly'),
    ('report-M8', 'August monthly'),
    ('report-M9', 'September monthly'),
    ('report-M10', 'October monthly'),
    ('report-M11', 'November monthly'),
    ('report-M12', 'December monthly'),
])

outreach_types = OrderedDict([
    ('Conferences', 'Conferences'),
    ('Roundtables', 'Round tables'),
])

meeting_types = OrderedDict([
    ('Open meetings', 'Open meeting'),
    ('Executive Sessions', 'Executive session'),
])

other_types = OrderedDict([
    ('Litigation', 'Litigation'),
    ('FEA Periods', 'FEA period'),
])

states = OrderedDict([
    ('AK', 'Alaska'),
    ('AL', 'Alabama'),
    ('AR', 'Arkansas'),
    ('AS', 'American Samoa'),
    ('AZ', 'Arizona'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DC', 'District of Columbia'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('GU', 'Guam'),
    ('HI', 'Hawaii'),
    ('IA', 'Iowa'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('MA', 'Massachusetts'),
    ('MD', 'Maryland'),
    ('ME', 'Maine'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MO', 'Missouri'),
    ('MP', 'Northern Mariana Islands'),
    ('MS', 'Mississippi'),
    ('MT', 'Montana'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('NE', 'Nebraska'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NV', 'Nevada'),
    ('NY', 'New York'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('PR', 'Puerto Rico'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VA', 'Virginia'),
    ('VI', 'Virgin Islands'),
    ('VT', 'Vermont'),
    ('WA', 'Washington'),
    ('WI', 'Wisconsin'),
    ('WV', 'West Virginia'),
    ('WY', 'Wyoming'),
])
