# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('election', 'All elections'), ('report-M', 'Monthly'), ('report-Q', 'Quarterly'), ('report-E', 'Pre- and post-election'), ('report-MY', 'Mid-Year'), ('report-YE', 'Year-End'), ('IE Periods', 'Independent expenditures'), ('EC Periods', 'Electioneering communications'), ('FEA Periods', 'Federal election activity periods'), ('Conferences', 'Conferences'), ('Roundtables', 'Webinars'), ('Open Meetings', 'Open meeting'), ('Executive Sessions', 'Executive session'), ('Public Hearings', 'Public hearing'), ('AOs and Rules', 'Advisory opinions and rulemakings')], max_length=255)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('value', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ManyToManyField(blank=True, to='cal.State'),
        ),
    ]
