# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import home.models
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# home.migrations.0002_create_homepage



def create_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    HomePage = apps.get_model('home.HomePage')

    # Delete the default homepage
    Page.objects.get(id=2).delete()

    # Create content type for homepage model
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage', app_label='home')

    # Create a new homepage
    homepage = HomePage.objects.create(
        title="Homepage",
        slug='home',
        content_type=homepage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
    )

    # Create a site with the new homepage set as the root
    Site.objects.create(
        hostname='localhost', root_page=homepage, is_default_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage),
    ]



def create_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    HomePage = apps.get_model('home.HomePage')

    # Delete the default homepage
    Page.objects.get(id=2).delete()

    # Create content type for homepage model
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage', app_label='home')

    # Create a new homepage
    homepage = HomePage.objects.create(
        title="Homepage",
        slug='home',
        content_type=homepage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
    )

    # Create a site with the new homepage set as the root
    Site.objects.create(
        hostname='localhost', root_page=homepage, is_default_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage),
    ]


def create_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    HomePage = apps.get_model('home.HomePage')

    # Delete the default homepage
    Page.objects.get(id=2).delete()

    # Create content type for homepage model
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage', app_label='home')

    # Create a new homepage
    homepage = HomePage.objects.create(
        title="Homepage",
        slug='home',
        content_type=homepage_content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/home/',
    )

    # Create a site with the new homepage set as the root
    Site.objects.create(
        hostname='localhost', root_page=homepage, is_default_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage),
    ]


class Migration(migrations.Migration):

    replaces = [(b'home', '0001_initial'), (b'home', '0002_create_homepage'), (b'home', '0003_auto_20150819_0342'), (b'home', '0004_checklistpage'), (b'home', '0005_auto_20150819_0517'), (b'home', '0006_auto_20150819_0546'), (b'home', '0007_auto_20150901_0442'), (b'home', '0008_auto_20150917_1906'), (b'home', '0009_contactpage'), (b'home', '0010_calendarpage'), (b'home', '0011_ssfchecklistpage'), (b'home', '0012_partychecklistpage'), (b'home', '0013_auto_20160427_2133'), (b'home', '0014_nonconnectedchecklistpage'), (b'home', '0015_custompage_content'), (b'home', '0016_auto_20160714_2359'), (b'home', '0017_auto_20160823_1504'), (b'home', '0018_record_digest_press_release'), (b'home', '0019_auto_20160908_2113'), (b'home', '0020_auto_20160909_0139'), (b'home', '0019_auto_20160907_2152'), (b'home', '0021_merge'), (b'home', '0022_auto_20160923_0004'), (b'home', '0023_remove_presslandingpage_feed_intro'), (b'home', '0024_presslandingpage_feed_intro'), (b'home', '0022_auto_20160921_2230'), (b'home', '0025_merge'), (b'home', '0026_auto_20161004_1620'), (b'home', '0027_auto_20161004_1620'), (b'home', '0025_auto_20161006_1415'), (b'home', '0028_merge'), (b'home', '0029_auto_20161107_0304'), (b'home', '0030_pressreleasepage_formatted_title'), (b'home', '0031_auto_20161201_2123'), (b'home', '0032_auto_20161201_2124'), (b'home', '0033_auto_20161201_2126'), (b'home', '0034_pressreleasepage_homepage_pin'), (b'home', '0035_pressreleasepage_homepage_hide'), (b'home', '0036_auto_20161216_0202'), (b'home', '0037_auto_20161216_0222'), (b'home', '0038_resourcepage'), (b'home', '0039_legalresourceslanding'), (b'home', '0040_auto_20161228_2356'), (b'home', '0041_enforcementpage'), (b'home', '0042_auto_20161229_2001'), (b'home', '0034_auto_20161221_1920'), (b'home', '0035_recordpage_monthly_issue'), (b'home', '0036_auto_20161221_2007'), (b'home', '0037_recordpage_monthly_issue_url'), (b'home', '0038_merge_20161223_1820'), (b'home', '0043_merge_20161230_0122'), (b'home', '0044_auto_20170105_0006'), (b'home', '0038_aboutlandingpage'), (b'home', '0039_aboutlandingpage_hero'), (b'home', '0040_aboutlandingpage_mission_intro'), (b'home', '0041_auto_20161227_1524'), (b'home', '0042_auto_20161227_1526'), (b'home', '0043_auto_20161227_1538'), (b'home', '0044_aboutlandingpage_option_blocks'), (b'home', '0045_merge_20170105_0036'), (b'home', '0046_auto_20170105_0038'), (b'home', '0047_auto_20170105_0044'), (b'home', '0048_auto_20170105_0049'), (b'home', '0049_auto_20170105_0052'), (b'home', '0050_auto_20170105_0055'), (b'home', '0051_commissionerpage'), (b'home', '0052_auto_20170111_2205'), (b'home', '0053_serviceslandingpage'), (b'home', '0054_auto_20170118_2104'), (b'home', '0055_tipsfortreasurerspage'), (b'home', '0055_auto_20170123_2232'), (b'home', '0056_merge_20170127_1735'), (b'home', '0057_auto_20170202_0237'), (b'home', '0058_documentfeedpage_documentpage'), (b'home', '0059_auto_20170209_0151'), (b'home', '0060_auto_20170209_2030'), (b'home', '0058_auto_20170210_2136'), (b'home', '0061_merge_20170210_2230'), (b'home', '0062_auto_20170214_2207'), (b'home', '0063_auto_20170214_2207'), (b'home', '0064_auto_20170215_2153'), (b'home', '0065_auto_20170221_2100')]

    initial = True

    dependencies = [
        ('wagtailredirects', '0002_add_verbose_names'),
        ('wagtailsearch', '0002_add_verbose_names'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0001_squashed_0016_change_page_url_path_to_text_field'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailimages', '0017_reduce_focal_point_key_max_length'),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0028_merge'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wagtailforms', '0002_add_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(
            code=create_homepage,
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())])),
                ('sidebar', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChecklistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SSFChecklistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PartyChecklistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NonconnectedChecklistPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='DigestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('read_next', models.ForeignKey(blank=True, default=home.models.get_previous_digest_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.DigestPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DigestPageAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('writer', 'Written by'), ('graphics', 'Graphics by'), ('contact', 'Contact')], default='author', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='home.DigestPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressReleasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[(b'audit reports', b'Audit reports'), (b'campaign finance data summaries', b'Campaign finance data summaries'), (b'commission appointments', b'Commission appointments'), (b'disclosure initiatives', b'Disclosure initiatives'), (b'enforcement matters', b'Enforcement matters'), (b'hearings', b'Hearings'), (b'litigation', b'Litigation'), (b'non-filer publications', b'Non-filer publications'), (b'open meetings and related matters', b'Open meetings and related matters'), (b'presidential public funds', b'Presidential public funds'), (b'rulemakings', b'Rulemakings'), (b'other agency actions', b'Other agency actions')], max_length=255)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('read_next', models.ForeignKey(blank=True, default=home.models.get_previous_press_release_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.PressReleasePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressReleasePageAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('writer', 'Written by'), ('graphics', 'Graphics by'), ('contact', 'Contact')], default='author', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='home.PressReleasePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[(b'advisory opinions', b'Advisory Opinions'), (b'commission', b'Commission'), (b'compliance', b'Compliance'), (b'litigation', b'Litigation'), (b'outreach', b'Outreach'), (b'public funding', b'Public Funding'), (b'regulations', b'Regulations'), (b'reporting', b'Reporting'), (b'statistics', b'Statistics')], max_length=255)),
                ('related_section_title', models.CharField(blank=True, default=b'Explore campaign finance data', max_length=255)),
                ('related_section_url', models.CharField(blank=True, default=b'/data/', max_length=255)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('read_next', models.ForeignKey(blank=True, default=home.models.get_previous_record_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.RecordPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecordPageAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('writer', 'Written by'), ('graphics', 'Graphics by'), ('contact', 'Contact')], default='author', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='home.RecordPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checklistpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='nonconnectedchecklistpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='partychecklistpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='ssfchecklistpage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='CollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('sidebar_title', models.CharField(blank=True, max_length=255, null=True)),
                ('related_pages', wagtail.wagtailcore.fields.StreamField([('related_pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock()))], blank=True, null=True)),
                ('sections', wagtail.wagtailcore.fields.StreamField([('section', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('check', 'Checklist'), ('bullet', 'Bulleted list')], default='bullet')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, null=False, required=False)), ('items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(classname='nothing')))]))])),
                ('show_search', models.BooleanField(choices=[(True, 'Show committee search box'), (False, 'Do not show committee search box')], default=False, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='digestpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='category',
            field=models.CharField(choices=[('advisory opinions', 'Advisory opinions'), ('commission', 'Commission'), ('compliance', 'Compliance'), ('litigation', 'Litigation'), ('outreach', 'Outreach'), ('public funding', 'Public funding'), ('regulations', 'Regulations'), ('reporting', 'Reporting'), ('statistics', 'Statistics')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='related_section_title',
            field=models.CharField(blank=True, default='Explore campaign finance data', max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='related_section_url',
            field=models.CharField(blank=True, default='/data/', max_length=255),
        ),
        migrations.CreateModel(
            name='PressLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('option_blocks', wagtail.wagtailcore.fields.StreamField([('option_blocks', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, null=False, required=False)), ('button_text', wagtail.wagtailcore.blocks.CharBlock(blank=False, null=False, required=False)), ('related_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))]))])),
                ('contact_intro', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('digest_intro', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('release_intro', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='digestpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='category',
            field=models.CharField(choices=[('advisory opinions', 'Advisory opinions'), ('commission', 'Commission'), ('compliance', 'Compliance'), ('litigation', 'Litigation'), ('outreach', 'Outreach'), ('public funding', 'Public funding'), ('regulations', 'Regulations'), ('reporting', 'Reporting'), ('statistics', 'Statistics')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='related_section_title',
            field=models.CharField(blank=True, default='Explore campaign finance data', max_length=255),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='related_section_url',
            field=models.CharField(blank=True, default='/data/', max_length=255),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions'), ('', '')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions')], max_length=255),
        ),
        migrations.AddField(
            model_name='pressreleasepage',
            name='formatted_title',
            field=models.CharField(blank=True, default='', help_text='Use if you need italics in the title. e.g. <em>Italicized words</em>', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], null=True)),
                ('sections', wagtail.wagtailcore.fields.StreamField([(b'sections', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'hide_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'Should the section title be displayed?', required=False)), (b'content', wagtail.wagtailcore.blocks.StreamBlock([(b'text', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, icon=b'pilcrow', null=False, required=False)), (b'documents', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())]), icon=b'doc-empty', template=b'blocks/section-documents.html')), (b'contact_info', wagtail.wagtailcore.blocks.StructBlock([(b'label', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'contact_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'item_label', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'item_icon', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'email', b'Email'), (b'fax', b'Fax'), (b'hand', b'Hand delivery'), (b'phone', b'Phone'), (b'mail', b'Mail')])), (b'item_info', wagtail.wagtailcore.blocks.RichTextBlock(required=True))])))])), (b'internal_button', wagtail.wagtailcore.blocks.StructBlock([(b'internal_page', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'external_button', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(template=b'blocks/page-links.html')), (b'document_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]), icon=b'doc-empty', template=b'blocks/document-list.html')), (b'current_commissioners', home.blocks.CurrentCommissionersBlock()), (b'fec_jobs', home.blocks.CareersBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())])), (b'aside', wagtail.wagtailcore.blocks.StreamBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'document', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_type', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'search', b'Search'), (b'calendar', b'Calendar')], help_text=b'Set an icon', icon=b'link', required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'coming_soon', wagtail.wagtailcore.blocks.BooleanBlock(required=False))]))], icon=b'placeholder', template=b'blocks/section-aside.html'))]))], null=True)),
                ('citations', wagtail.wagtailcore.fields.StreamField([('citations', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('label', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description'))])))], null=True)),
                ('related_topics', wagtail.wagtailcore.fields.StreamField([('related_topics', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock(label='Related topic')))], null=True)),
                ('breadcrumb_style', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Red')], default='primary', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalResourcesLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EnforcementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.RecordPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions'), ('', '')], max_length=255),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='monthly_issue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RecordPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.RecordPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_recordpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recordpage',
            name='monthly_issue_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AboutLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('sections', wagtail.wagtailcore.fields.StreamField([('sections', wagtail.wagtailcore.blocks.StructBlock([('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, null=False, required=False)), ('button_text', wagtail.wagtailcore.blocks.CharBlock(blank=False, null=False, required=False)), ('related_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))]))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CommissionerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_initial', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('sworn_in', models.DateField(blank=True, null=True)),
                ('term_expiration', models.DateField(blank=True, null=True)),
                ('party_affiliation', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=2)),
                ('commissioner_title', models.CharField(blank=True, max_length=255)),
                ('commissioner_bio', wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True, null=True)),
                ('commissioner_email', models.CharField(blank=True, max_length=255)),
                ('commissioner_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioner_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('reappointed_dates', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('hero', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('intro', wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], null=True)),
                ('sections', wagtail.wagtailcore.fields.StreamField([(b'sections', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'hide_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'Should the section title be displayed?', required=False)), (b'content', wagtail.wagtailcore.blocks.StreamBlock([(b'text', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, icon=b'pilcrow', null=False, required=False)), (b'documents', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())]), icon=b'doc-empty', template=b'blocks/section-documents.html')), (b'contact_info', wagtail.wagtailcore.blocks.StructBlock([(b'label', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'contact_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'item_label', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'item_icon', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'email', b'Email'), (b'fax', b'Fax'), (b'hand', b'Hand delivery'), (b'phone', b'Phone'), (b'mail', b'Mail')])), (b'item_info', wagtail.wagtailcore.blocks.RichTextBlock(required=True))])))])), (b'internal_button', wagtail.wagtailcore.blocks.StructBlock([(b'internal_page', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'external_button', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(template=b'blocks/page-links.html')), (b'document_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]), icon=b'doc-empty', template=b'blocks/document-list.html')), (b'current_commissioners', home.blocks.CurrentCommissionersBlock()), (b'fec_jobs', home.blocks.CareersBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())])), (b'aside', wagtail.wagtailcore.blocks.StreamBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(icon=b'title', required=False)), (b'document', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock())])), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_type', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'search', b'Search'), (b'calendar', b'Calendar')], help_text=b'Set an icon', icon=b'link', required=False)), (b'url', wagtail.wagtailcore.blocks.URLBlock()), (b'text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'coming_soon', wagtail.wagtailcore.blocks.BooleanBlock(required=False))]))], icon=b'placeholder', template=b'blocks/section-aside.html'))]))], null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TipsForTreasurersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('read_next', models.ForeignKey(blank=True, default=home.models.get_previous_tips_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TipsForTreasurersPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DocumentFeedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('intro', wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('category', models.CharField(choices=[('oig', 'oig'), ('strategy_budget_performance', 'strategy budget performance'), ('foia', 'foia'), ('privacy', 'privacy'), ('procurement_contracting_reports', 'procurement contracting reports'), ('annual_anniversary', 'annual anniversary'), ('agency_operations', 'agency operations')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('audit report', 'Audit report'), ('inspection report', 'Inspection report'), ('special review report', 'Special review report'), ('semiannual report', 'Semiannual report'), ('strategic plan', 'Strategic plan'), ('it strategic plan', 'IT strategic plan'), ('congressional budget justification', 'Congressional budget justification'), ('annual performance report', 'Annual performance report'), ('performance and accountability report', 'Performance and accountability report'), ('annual foia report', 'Annual FOIA report'), ('privacy act notices', 'Privacy Act notices'), ('privacy policy', 'Privacy policy'), ('purchase inventory', 'Purchase inventory'), ('annual report', 'Annual report'), ('fair act inventory report', 'FAIR Act inventory report'), ('request for proposal (rfp)', 'Request for proposal (RFP)'), ('anniversary report', 'Anniversary report'), ('shutdown plan', 'Shutdown plan'), ('operation plan', 'Operation plan')], max_length=255, null=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
