# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160427_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('table', wagtail.contrib.table_block.blocks.TableBlock()),)),
            preserve_default=False,
        ),
    ]
