# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0019_auto_20160902_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='collectionpage',
            name='related_pages_sidebar',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='other_pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Page', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='sidebar_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
