# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160907_2152'),
        ('home', '0020_auto_20160909_0139'),
    ]

    operations = [
    ]
