# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 23:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160902_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='other_pages',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='related_pages',
            field=wagtail.wagtailcore.fields.StreamField((('related_pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock())),), blank=True, null=True),
        ),
    ]
