# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 22:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presslandingpage',
            old_name='feed_intro',
            new_name='digest_intro',
        ),
        migrations.AddField(
            model_name='presslandingpage',
            name='release_intro',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())), blank=True, null=True),
        ),
    ]
