# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20160921_2230'),
        ('home', '0024_presslandingpage_feed_intro'),
    ]

    operations = [
    ]
