# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 23:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20160902_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('list--checks', 'Checklist'), ('list--bulleted', 'Bulleted list')], default='bulleted')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, null=True)), ('items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock()))))),)),
        ),
    ]
