# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presslandingpage',
            name='digest_intro',
        ),
        migrations.RemoveField(
            model_name='presslandingpage',
            name='release_intro',
        ),
    ]
