# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 23:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20160902_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('list--checks list--checks--secondary', 'Checklist'), ('list--bulleted', 'Bulleted list')], default='list--bulleted')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, null=False, required=False)), ('items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.RichTextBlock(classname='nothing')))))),)),
        ),
    ]
