# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20161006_1415'),
        ('home', '0027_auto_20161004_1620'),
    ]

    operations = [
    ]
