# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-03 00:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20160902_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='show_search',
            field=wagtail.wagtailcore.fields.StreamField((('show_search', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(True, 'Show committee search box'), (False, 'Do not show committee search box')], default=False)),), blank=True, null=True),
        ),
    ]
