# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_collectionpage_show_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='show_search',
            field=models.CharField(blank=True, choices=[(True, 'Show committee search box'), (False, 'Do not show committee search box')], default=False, max_length=255, null=True),
        ),
    ]
