# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('mtg_date', models.DateField(default=datetime.date.today)),
                ('mtg_time', models.CharField(default='10:00 AM', max_length=255)),
                ('agenda', wagtail.wagtailcore.fields.StreamField((('mtg_media', wagtail.wagtailcore.blocks.StreamBlock((('full_video_url', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('full_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)), ('mtg_transcript', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False))))), ('agenda_item', wagtail.wagtailcore.blocks.StreamBlock((('item_title', wagtail.wagtailcore.blocks.TextBlock()), ('item_text', wagtail.wagtailcore.blocks.TextBlock()), ('mtg_doc', wagtail.wagtailcore.blocks.StructBlock((('mtg_doc_upload', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=True)), ('submitted_late', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Submitted Late', required=False)), ('heldover', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Held Over', required=False)), ('heldover_from', wagtail.wagtailcore.blocks.DateBlock(help_text='Held Over From', required=False))))), ('item_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)))))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='presslandingpage',
            old_name='digest_intro',
            new_name='feed_intro',
        ),
        migrations.RemoveField(
            model_name='presslandingpage',
            name='release_intro',
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='category',
            field=models.CharField(choices=[('audit reports', 'Audit reports'), ('campaign finance data summaries', 'Campaign finance data summaries'), ('commission appointments', 'Commission appointments'), ('disclosure initiatives', 'Disclosure initiatives'), ('enforcement matters', 'Enforcement matters'), ('hearings', 'Hearings'), ('litigation', 'Litigation'), ('non-filer publications', 'Non-filer publications'), ('open meetings and related matters', 'Open meetings and related matters'), ('presidential public funds', 'Presidential public funds'), ('rulemakings', 'Rulemakings'), ('other agency actions', 'Other agency actions')], max_length=255),
        ),
    ]
