# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20161107_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleasepage',
            name='formatted_title',
            field=models.CharField(blank=True, help_text='Use if you need italics in the title', max_length=255, null=True),
        ),
    ]
