# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-03 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20160903_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpage',
            name='show_search',
            field=models.BooleanField(choices=[(True, 'Show committee search box'), (False, 'Do not show committee search box')], default=False, max_length=255),
        ),
    ]
