# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 19:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20161019_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapage',
            name='mtg_media',
            field=wagtail.wagtailcore.fields.StreamField((('full_video_url', wagtail.wagtailcore.blocks.TextBlock()), ('full_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)), ('mtg_transcript', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)))),
        ),
    ]
