# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_pressreleasepage_formatted_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressreleasepage',
            old_name='formatted_title',
            new_name='rich_title',
        ),
    ]
