# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20161201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressreleasepage',
            name='formatted_title',
            field=models.CharField(blank=True, default='', help_text='Use if you need italics in the title. e.g. <em>Italicized words</em>', max_length=255, null=True),
        ),
    ]
