# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20161201_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin',
            field=models.BooleanField(default=False),
        ),
    ]
