# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20161221_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpage',
            name='monthly_issue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
