# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_pressreleasepage_homepage_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpage',
            name='homepage_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin',
            field=models.BooleanField(default=False),
        ),
    ]
