# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20161216_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
