# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20161221_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpage',
            name='monthly_issue_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
