# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_recordpage_monthly_issue_url'),
        ('home', '0037_auto_20161216_0222'),
    ]

    operations = [
    ]
