# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_aboutlandingpage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlandingpage',
            name='mission_intro',
            field=wagtail.fields.StreamField([(b'heading', wagtail.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.blocks.RichTextBlock()), (b'html', wagtail.blocks.RawHTMLBlock()), (b'image', wagtail.images.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True),
        ),
    ]
