# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_enforcementpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalResourcesLanding',
            new_name='LegalResourcesLandingPage',
        ),
    ]
