# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20161227_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutlandingpage',
            old_name='org_report_intro',
            new_name='reports_intro',
        ),
    ]
