# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_merge_20161223_1820'),
        ('home', '0042_auto_20161229_2001'),
    ]

    operations = [
    ]
