# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20161227_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlandingpage',
            name='option_blocks',
            field=wagtail.core.fields.StreamField([(b'option_blocks', wagtail.core.blocks.StructBlock([(b'title', wagtail.core.blocks.CharBlock(required=True)), (b'intro', wagtail.core.blocks.RichTextBlock(blank=False, null=False, required=False)), (b'button_text', wagtail.core.blocks.CharBlock(blank=False, null=False, required=True)), (b'related_page', wagtail.core.blocks.PageChooserBlock())]))], default=''),
            preserve_default=False,
        ),
    ]
