# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_aboutlandingpage_option_blocks'),
        ('home', '0043_merge_20161230_0122'),
    ]

    operations = [
    ]
