# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20170105_0006'),
        ('home', '0044_aboutlandingpage_option_blocks'),
    ]

    operations = [
    ]
