# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0031_auto_20170109_0550'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('home', '0044_auto_20170105_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_initial', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('sworn_in', models.DateField(blank=True, null=True)),
                ('term_expiration', models.DateField(blank=True, null=True)),
                ('party_affiliation', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=2)),
                ('commissioner_title', models.CharField(blank=True, max_length=255)),
                ('commissioner_bio', wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),), blank=True, null=True)),
                ('commissioner_email', models.CharField(blank=True, max_length=255)),
                ('commissioner_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioner_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
