# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20170105_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='intro',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
