# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_commissionerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionerpage',
            name='reappointed_dates',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='sections',
            field=wagtail.fields.StreamField((('sections', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('hide_title', wagtail.blocks.BooleanBlock(help_text='Should the section title be displayed?', required=False)), ('content', wagtail.blocks.StreamBlock((('text', wagtail.blocks.RichTextBlock(blank=False, icon='pilcrow', null=False, required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock()))), icon='doc-empty', template='blocks/section-documents.html')), ('contact_info', wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('item_label', wagtail.blocks.CharBlock(required=True)), ('item_icon', wagtail.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail')])), ('item_info', wagtail.blocks.RichTextBlock(required=True))))))))), ('internal_button', wagtail.blocks.StructBlock((('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())))), ('external_button', wagtail.blocks.StructBlock((('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())))), ('page', wagtail.blocks.PageChooserBlock(template='blocks/page-links.html')), ('document_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()))), icon='doc-empty', template='blocks/document-list.html'))))), ('aside', wagtail.blocks.StreamBlock((('title', wagtail.blocks.CharBlock(icon='title', required=False)), ('document', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())))), ('link', wagtail.blocks.StructBlock((('link_type', wagtail.blocks.ChoiceBlock(choices=[('search', 'Search'), ('calendar', 'Calendar')], help_text='Set an icon', icon='link', required=False)), ('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock(required=True)), ('coming_soon', wagtail.blocks.BooleanBlock(required=False)))))), icon='placeholder', template='blocks/section-aside.html'))))),), null=True),
        ),
    ]
