# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20170111_2219'),
        ('home', '0052_auto_20170111_2205'),
    ]

    operations = [
    ]
