# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20161019_1936'),
        ('home', '0054_auto_20170118_2104'),
    ]

    operations = [
    ]
