# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_tipsfortreasurerspage'),
        ('home', '0055_auto_20170123_2232'),
    ]

    operations = [
    ]
