# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_documentfeedpage_documentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
