# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20170209_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfeedpage',
            name='category',
            field=models.CharField(choices=[('oig', 'oig'), ('privacy', 'privacy'), ('procurement_contracting_reports', 'procurement contracting reports'), ('strategy_budget_performance', 'strategy budget performance'), ('annual_anniversary', 'annual anniversary'), ('agency_operations', 'agency operations'), ('foia', 'foia')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='category',
            field=models.CharField(choices=[('anniversary report', 'Anniversary report'), ('annual performance report', 'Annual performance report'), ('audit report', 'Audit report'), ('it strategic plan', 'IT strategic plan'), ('strategic plan', 'Strategic plan'), ('semiannual report', 'Semiannual report'), ('purchase inventory', 'Purchase inventory'), ('request for proposal (rfp)', 'Request for proposal (RFP)'), ('operation plan', 'Operation plan'), ('special review report', 'Special review report'), ('annual foia report', 'Annual FOIA report'), ('privacy policy', 'Privacy policy'), ('congressional budget justification', 'Congressional budget justification'), ('privacy act notices', 'Privacy Act notices'), ('inspection report', 'Inspection report'), ('performance and accountability report', 'Performance and accountability report'), ('annual report', 'Annual report'), ('shutdown plan', 'Shutdown plan'), ('fair act inventory report', 'FAIR Act inventory report')], max_length=255, null=True),
        ),
    ]
