# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20170209_2030'),
        ('home', '0058_auto_20170210_2136'),
    ]

    operations = [
    ]
