# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20170214_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsfortreasurerspage',
            name='read_next',
            field=models.ForeignKey(blank=True, default=home.models.get_previous_tips_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TipsForTreasurersPage'),
        ),
    ]
