# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20170214_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleasepage',
            name='homepage_pin_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordpage',
            name='homepage_pin_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
