# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20170215_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipsfortreasurerspage',
            name='homepage_hide',
        ),
        migrations.RemoveField(
            model_name='tipsfortreasurerspage',
            name='homepage_pin',
        ),
        migrations.RemoveField(
            model_name='tipsfortreasurerspage',
            name='homepage_pin_expiration',
        ),
        migrations.RemoveField(
            model_name='tipsfortreasurerspage',
            name='homepage_pin_start',
        ),
    ]
