# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20170215_2153'),
        ('home', '0055_merge_20170122_0109'),
    ]

    operations = [
    ]
