# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20170221_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutlandingpage',
            name='hero',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))]),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='sidebar',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digestpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentfeedpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enforcementpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalresourceslandingpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonconnectedchecklistpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partychecklistpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presslandingpage',
            name='contact_intro',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presslandingpage',
            name='digest_intro',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presslandingpage',
            name='hero',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presslandingpage',
            name='release_intro',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslandingpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslandingpage',
            name='hero',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssfchecklistpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipsfortreasurerspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
