# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20170221_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='file_name',
        ),
    ]
