# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_remove_documentpage_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='year_only',
            field=models.BooleanField(default=False),
        ),
    ]
