# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_remove_documentpage_file_name'),
        ('home', '0066_auto_20170302_0507'),
    ]

    operations = [
    ]
