# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0066_remove_documentpage_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('mtg_date', models.DateTimeField(default=datetime.date.today)),
                ('mtg_time', models.TimeField(default=datetime.time(10, 0))),
                ('mtg_media', wagtail.wagtailcore.fields.StreamField((('full_video_url', wagtail.wagtailcore.blocks.TextBlock()), ('full_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)), ('mtg_transcript', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False))))),
                ('agenda', wagtail.wagtailcore.fields.StreamField((('agenda_item', wagtail.wagtailcore.blocks.StreamBlock((('item_title', wagtail.wagtailcore.blocks.TextBlock()), ('item_text', wagtail.wagtailcore.blocks.TextBlock()), ('mtg_doc', wagtail.wagtailcore.blocks.StructBlock((('mtg_doc_upload', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=True)), ('submitted_late', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Submitted Late', required=False)), ('heldover', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Held Over', required=False)), ('heldover_from', wagtail.wagtailcore.blocks.DateBlock(help_text='Held Over From', required=False))))), ('item_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False))))),))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
