# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_merge_20170306_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportslandingpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'custom_table', wagtail.wagtailcore.blocks.StructBlock([(b'custom_table', wagtail.contrib.table_block.blocks.TableBlock()), (b'title', wagtail.wagtailcore.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
