# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_documentpage_year_only'),
        ('home', '0067_agendapage'),
    ]

    operations = [
    ]
