# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_merge_20170310_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='category',
            field=models.CharField(blank=True, choices=[('audit report', 'Audit report'), ('inspection or special review report', 'Inspection or special review report'), ('semiannual reportstrategic plan', 'Semiannual reportStrategic plan'), ('work plan', 'Work plan'), ('annual financial report', 'Annual financial report'), ('annual performance report', 'Annual performance report'), ('congressional submission', 'Congressional submission'), ('it strategic plan', 'IT strategic plan'), ('performance and accountability report', 'Performance and accountability report'), ('strategic plan', 'Strategic plan'), ('annual report', 'Annual report'), ('summary report', 'Summary report'), ('privacy act notices', 'Privacy Act notices'), ('privacy policy', 'Privacy policy'), ('inventory', 'Inventory'), ('memo', 'Memo'), ('request for proposal', 'Request for proposal'), ('anniversary report', 'Anniversary report'), ('operation plan', 'Operation plan'), ('shutdown plan', 'Shutdown plan'), ('study', 'Study')], help_text='If this is a report, add a category', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='category',
            field=models.CharField(choices=[('audit report', 'Audit report'), ('inspection or special review report', 'Inspection or special review report'), ('semiannual reportstrategic plan', 'Semiannual reportStrategic plan'), ('work plan', 'Work plan'), ('annual financial report', 'Annual financial report'), ('annual performance report', 'Annual performance report'), ('congressional submission', 'Congressional submission'), ('it strategic plan', 'IT strategic plan'), ('performance and accountability report', 'Performance and accountability report'), ('strategic plan', 'Strategic plan'), ('annual report', 'Annual report'), ('summary report', 'Summary report'), ('privacy act notices', 'Privacy Act notices'), ('privacy policy', 'Privacy policy'), ('inventory', 'Inventory'), ('memo', 'Memo'), ('request for proposal', 'Request for proposal'), ('anniversary report', 'Anniversary report'), ('operation plan', 'Operation plan'), ('shutdown plan', 'Shutdown plan'), ('study', 'Study')], max_length=255, null=True),
        ),
    ]
