# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20170315_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='category',
            field=models.CharField(blank=True, choices=[('audit report', 'Audit report'), ('work plan', 'Work plan'), ('inspection or special review report', 'Inspection or special review report'), ('strategic plan', 'Strategic plan'), ('semiannual report', 'Semiannual report'), ('it strategic plan', 'IT strategic plan'), ('congressional submission', 'Congressional submission'), ('annual performance report', 'Annual performance report'), ('annual financial report', 'Annual financial report'), ('performance and accountability report', 'Performance and accountability report'), ('annual report', 'Annual report'), ('summary report', 'Summary report'), ('privacy act notices', 'Privacy Act notices'), ('privacy policy', 'Privacy policy'), ('inventory', 'Inventory'), ('memo', 'Memo'), ('request for proposal', 'Request for proposal'), ('anniversary report', 'Anniversary report'), ('shutdown plan', 'Shutdown plan'), ('operation plan', 'Operation plan')], help_text='If this is a report, add a category', max_length=255, null=True),
        ),
    ]
