# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20170316_0006'),
        ('home', '0069_auto_20170318_0005'),
    ]

    operations = [
    ]
