# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 02:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20170317_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='citations',
            field=wagtail.wagtailcore.fields.StreamField((('citations', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description')))))),), null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='record_articles',
            field=wagtail.wagtailcore.fields.StreamField((('record_articles', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock(target_model='home.RecordPage'))),), null=True),
        ),
    ]
