# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 02:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20170317_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='continue_learning',
            field=wagtail.wagtailcore.fields.StreamField((('continue_learning', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock()))), icon='doc-empty')),), null=True),
        ),
    ]
