# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_agendapage_imported_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapage',
            name='mtg_media',
            field=wagtail.wagtailcore.fields.StreamField((('full_video_url', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('full_audio_url', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('mtg_transcript_url', wagtail.wagtailcore.blocks.TextBlock(required=False)))),
        ),
    ]
