# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20170324_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendapage',
            old_name='mtg_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='agendapage',
            name='mtg_date',
        ),
        migrations.AddField(
            model_name='agendapage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
