# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20170329_2112'),
        ('home', '0073_auto_20170330_1915'),
        ('home', '0073_auto_20170330_1840'),
    ]

    operations = [
    ]
