# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 22:22
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0073_auto_20170330_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enforcementpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='enforcementpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('sections', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('hide_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Should the section title be displayed?', required=False)), ('content', wagtail.wagtailcore.blocks.StreamBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, icon='pilcrow', null=False, required=False)), ('documents', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock()))), icon='doc-empty', template='blocks/section-documents.html')), ('contact_info', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('item_label', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('item_icon', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail')])), ('item_info', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))))))), ('internal_button', wagtail.wagtailcore.blocks.StructBlock((('internal_page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('external_button', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(template='blocks/page-links.html')), ('disabled_page', wagtail.wagtailcore.blocks.CharBlock(blank=False, help_text='Name of a disabled link', icon='placeholder', null=False, required=False, template='blocks/disabled-page-links.html')), ('document_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()))), icon='doc-empty', template='blocks/document-list.html')), ('current_commissioners', home.blocks.CurrentCommissionersBlock()), ('fec_jobs', home.blocks.CareersBlock()), ('mur_search', home.blocks.MURSearchBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())))), ('aside', wagtail.wagtailcore.blocks.StreamBlock((('title', wagtail.wagtailcore.blocks.CharBlock(icon='title', required=False)), ('document', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('link', wagtail.wagtailcore.blocks.StructBlock((('link_type', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('search', 'Search'), ('calendar', 'Calendar'), ('record', 'Record')], help_text='Set an icon', icon='link', required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('coming_soon', wagtail.wagtailcore.blocks.BooleanBlock(required=False)))))), icon='placeholder', template='blocks/section-aside.html'))))),), null=True),
        ),
        migrations.AlterField(
            model_name='serviceslandingpage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('sections', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('hide_title', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Should the section title be displayed?', required=False)), ('content', wagtail.wagtailcore.blocks.StreamBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=False, icon='pilcrow', null=False, required=False)), ('documents', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock()))), icon='doc-empty', template='blocks/section-documents.html')), ('contact_info', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('item_label', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('item_icon', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail')])), ('item_info', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))))))), ('internal_button', wagtail.wagtailcore.blocks.StructBlock((('internal_page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('external_button', wagtail.wagtailcore.blocks.StructBlock((('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(template='blocks/page-links.html')), ('disabled_page', wagtail.wagtailcore.blocks.CharBlock(blank=False, help_text='Name of a disabled link', icon='placeholder', null=False, required=False, template='blocks/disabled-page-links.html')), ('document_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()))), icon='doc-empty', template='blocks/document-list.html')), ('current_commissioners', home.blocks.CurrentCommissionersBlock()), ('fec_jobs', home.blocks.CareersBlock()), ('mur_search', home.blocks.MURSearchBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())))), ('aside', wagtail.wagtailcore.blocks.StreamBlock((('title', wagtail.wagtailcore.blocks.CharBlock(icon='title', required=False)), ('document', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('link', wagtail.wagtailcore.blocks.StructBlock((('link_type', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('search', 'Search'), ('calendar', 'Calendar'), ('record', 'Record')], help_text='Set an icon', icon='link', required=False)), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('coming_soon', wagtail.wagtailcore.blocks.BooleanBlock(required=False)))))), icon='placeholder', template='blocks/section-aside.html'))))),), null=True),
        ),
        migrations.DeleteModel(
            name='EnforcementPage',
        ),
    ]
