# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20170329_2112'),
        ('home', '0074_auto_20170330_2222'),
    ]

    operations = [
    ]
