# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_merge_20170330_2316'),
        ('home', '0075_auto_20170330_2354'),
        ('home', '0075_merge_20170331_0608'),
    ]

    operations = [
    ]
