# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_auto_20170331_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='category',
            field=models.CharField(choices=[('audit report', 'Audit report'), ('inspection or special review report', 'Inspection or special review report'), ('semiannual report', 'Semiannual report'), ('strategic plan', 'Strategic plan'), ('work plan', 'Work plan'), ('annual performance report', 'Annual performance report'), ('agency financial report', 'Agency Financial Report'), ('congressional submission', 'Congressional submission'), ('it strategic plan', 'IT strategic plan'), ('performance and accountability report', 'Performance and accountability report'), ('summary of performance and financial information', 'Summary of performance and financial information'), ('annual report', 'Annual report'), ('summary report', 'Summary report'), ('privacy act notice', 'Privacy Act notice'), ('privacy policy', 'Privacy policy'), ('buy america report', 'Buy America report'), ('fair act', 'FAIR Act'), ('inventory', 'Inventory'), ('memo', 'Memo'), ('public procurement report', 'Public procurement report'), ('request for proposal', 'Request for proposal'), ('anniversary report', 'Anniversary report'), ('gift reports', 'Gift reports'), ('shutdown plan', 'Shutdown plan'), ('study', 'Study')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='category',
            field=models.CharField(blank=True, choices=[('audit report', 'Audit report'), ('inspection or special review report', 'Inspection or special review report'), ('semiannual report', 'Semiannual report'), ('strategic plan', 'Strategic plan'), ('work plan', 'Work plan'), ('annual performance report', 'Annual performance report'), ('agency financial report', 'Agency Financial Report'), ('congressional submission', 'Congressional submission'), ('it strategic plan', 'IT strategic plan'), ('performance and accountability report', 'Performance and accountability report'), ('summary of performance and financial information', 'Summary of performance and financial information'), ('annual report', 'Annual report'), ('summary report', 'Summary report'), ('privacy act notice', 'Privacy Act notice'), ('privacy policy', 'Privacy policy'), ('buy america report', 'Buy America report'), ('fair act', 'FAIR Act'), ('inventory', 'Inventory'), ('memo', 'Memo'), ('public procurement report', 'Public procurement report'), ('request for proposal', 'Request for proposal'), ('anniversary report', 'Anniversary report'), ('gift reports', 'Gift reports'), ('shutdown plan', 'Shutdown plan'), ('study', 'Study')], help_text='If this is a report, add a category', max_length=255, null=True),
        ),
    ]
