# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0078_auto_20170404_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='checklistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='nonconnectedchecklistpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='nonconnectedchecklistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='partychecklistpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='partychecklistpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='ssfchecklistpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='ssfchecklistpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ChecklistPage',
        ),
        migrations.DeleteModel(
            name='NonconnectedChecklistPage',
        ),
        migrations.DeleteModel(
            name='PartyChecklistPage',
        ),
        migrations.DeleteModel(
            name='SSFChecklistPage',
        ),
    ]
