# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20170414_0021'),
        ('home', '0081_genericupdate'),
        ('home', '0081_auto_20170501_2216'),
    ]

    operations = [
    ]
