# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_genericupdate'),
        ('home', '0081_auto_20170501_2216'),
    ]

    operations = [
    ]
