# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_merge_20170504_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapage',
            name='approved_minutes_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='approved_minutes_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='draft_minutes_links',
            field=models.TextField(blank=True, help_text='URLs separated by a newline'),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='live_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='meeting_type',
            field=models.CharField(choices=[('O', 'Open'), ('E', 'Executive')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='agendapage',
            name='sunshine_act_links',
            field=models.TextField(blank=True, help_text='URLs separated by a newline'),
        ),
        migrations.AlterField(
            model_name='agendapage',
            name='agenda',
            field=wagtail.core.fields.StreamField((('agenda_item', wagtail.core.blocks.StreamBlock((('item_title', wagtail.core.blocks.TextBlock()), ('item_text', wagtail.core.blocks.RichTextBlock()), ('item_audio', wagtail.documents.blocks.DocumentChooserBlock(required=False))))),)),
        ),
    ]
