# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20170506_0059'),
        ('home', '0083_auto_20170504_2215'),
    ]

    operations = [
    ]
