# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_merge_20170509_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaPage',
            new_name='MeetingPage',
        ),
    ]
