# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_auto_20170510_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingpage',
            name='mtg_media',
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='full_audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='full_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='live_video_captions',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='mtg_transcript_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='agenda',
            field=wagtail.wagtailcore.fields.StreamField((('agenda_item', wagtail.wagtailcore.blocks.StructBlock((('item_title', wagtail.wagtailcore.blocks.TextBlock()), ('item_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('item_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False))))),)),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='meeting_type',
            field=models.CharField(choices=[('O', 'Open meeting'), ('E', 'Executive session')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='time',
            field=models.TimeField(blank=True, help_text='If no time is entered the time will be set to 10 a.m.', null=True),
        ),
    ]
