# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_auto_20170510_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='show_contact_card',
            field=models.BooleanField(choices=[(True, 'Show contact card'), (False, 'Do not show contact card')], default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='custompage',
            name='show_contact_link',
            field=models.BooleanField(choices=[(True, 'Show contact link'), (False, 'Do not show contact link')], default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='show_contact_card',
            field=models.BooleanField(choices=[(True, 'Show contact card'), (False, 'Do not show contact card')], default=False, max_length=255),
        ),
    ]
