# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0085_auto_20170510_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='meetingpage',
            name='mtg_media',
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='show_contact_card',
            field=models.BooleanField(choices=[(True, 'Show contact card'), (False, 'Do not show contact card')], default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='custompage',
            name='show_contact_link',
            field=models.BooleanField(choices=[(True, 'Show contact link'), (False, 'Do not show contact link')], default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='full_audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='full_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='live_video_captions',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingpage',
            name='mtg_transcript_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='show_contact_card',
            field=models.BooleanField(choices=[(True, 'Show contact card'), (False, 'Do not show contact card')], default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='agenda',
            field=wagtail.core.fields.StreamField((('agenda_item', wagtail.core.blocks.StructBlock((('item_title', wagtail.core.blocks.TextBlock()), ('item_text', wagtail.core.blocks.RichTextBlock(required=False)), ('item_audio', wagtail.documents.blocks.DocumentChooserBlock(required=False))))),)),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='meeting_type',
            field=models.CharField(choices=[('O', 'Open meeting'), ('E', 'Executive session')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='time',
            field=models.TimeField(blank=True, help_text='If no time is entered the time will be set to 10 a.m.', null=True),
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
