# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 00:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20170517_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpage',
            name='agenda',
            field=wagtail.wagtailcore.fields.StreamField((('agenda_item', wagtail.wagtailcore.blocks.StructBlock((('item_title', wagtail.wagtailcore.blocks.TextBlock()), ('item_text', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('item_audio', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False))))),)),
        ),
    ]
