# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20170519_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpage',
            name='homepage_hide',
            field=models.BooleanField(default=False),
        ),
    ]
