# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0087_meetingpage_homepage_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerAnnouncement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.CharField(max_length=255)),
                ('link_title', models.CharField(max_length=255)),
                ('link_url', models.URLField(max_length=255)),
                ('link_title_2', models.CharField(blank=True, max_length=255)),
                ('link_url_2', models.URLField(blank=True, max_length=255)),
                ('date_active', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='genericupdate',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GenericUpdate',
        ),
    ]
