# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20170517_2153'),
        ('home', '0087_auto_20170517_0037'),
    ]

    operations = [
    ]
