# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_meetingpage_homepage_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionLimitsChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
