# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0088_merge_20170519_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
