# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_auto_20170811_1840'),
        ('home', '0088_folder'),
    ]

    operations = [
    ]
