# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_folder'),
        ('home', '0090_auto_20170811_1840'),
    ]

    operations = [
    ]
