# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_auto_20170814_0109'),
        ('home', '0091_merge_20170811_2035'),
    ]

    operations = [
    ]
