# -*- coding: utf-8 -*-

# Generated by Django 1.10.7 on 2017-08-25 10:52

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('home', '0093_merge_20170814_2229'),
        ('home', '0091_merge_20170814_0055'),
    ]

    operations = [
    ]
