# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 01:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_auto_20170829_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpage',
            name='sunshine_act_doc_upld',
            field=wagtail.wagtailcore.fields.StreamField((('sunshine_act_upld', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)),), blank=True, null=True),
        ),
    ]
