# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20170831_2013'),
        ('home', '0095_meetingpage_sunshine_act_doc_upld'),
    ]

    operations = [
    ]
