# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 19:52
from __future__ import unicode_literals

from django.db import migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0096_merge_20170907_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannerannouncement',
            name='date_inactive',
            field=models.DateTimeField(null=True),
        )
    ]
