# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 04:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0097_auto_20170929_2329'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='serviceslandingpage',
            name='sections',
        ),
        migrations.AddField(
            model_name='serviceslandingpage',
            name='you_might_also_like',
            field=wagtail.wagtailcore.fields.StreamField((('you_might_also_like_item', wagtail.wagtailcore.blocks.StructBlock((('item_title', wagtail.wagtailcore.blocks.TextBlock()), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_url', wagtail.wagtailcore.blocks.URLBlock())))))))),), blank=True, null=True),
        ),

    ]
