# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0098_auto_20170930_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
