# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-09 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20170925_1952'),
        ('home', '0098_auto_20170930_0054'),
    ]

    operations = [
    ]
