# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0099_merge_20171109_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerAlert',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('alert_description', models.CharField(blank=True, max_length=255)),
                ('alert_link_title', models.CharField(blank=True, max_length=255)),
                ('alert_link_url', models.URLField(blank=True, max_length=255)),
                ('alert_link_title_2', models.CharField(blank=True, max_length=255)),
                ('alert_link_url_2', models.URLField(blank=True, max_length=255)),
                ('alert_date_active', models.DateTimeField()),
                ('alert_date_inactive', models.DateTimeField(null=True)),
                ('alert_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepagebannerannouncement',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagebannerannouncement',
            name='link_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagebannerannouncement',
            name='link_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
