# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 02:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_auto_20170930_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslandingpage',
            name='you_might_also_like',
            field=wagtail.wagtailcore.fields.StreamField((('you_might_also_like_section', wagtail.wagtailcore.blocks.StructBlock((('section_title', wagtail.wagtailcore.blocks.TextBlock()), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_url', wagtail.wagtailcore.blocks.URLBlock())))))))),), blank=True, null=True),
        ),
    ]
