# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20180124_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanneralert',
            name='alert_link_title_2',
        ),
        migrations.RemoveField(
            model_name='homepagebanneralert',
            name='alert_link_url_2',
        ),
        migrations.AlterField(
            model_name='homepagebanneralert',
            name='alert_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepagebanneralert',
            name='alert_description',
            field=models.CharField(blank=True, help_text='This feature requires approval by Amy Kort or Wei Luo prior to deployment.', max_length=255),
        ),
    ]
