# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20180126_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpage',
            name='show_streaming_info',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide live video and live captions links'),
        ),
    ]
