# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20180126_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpage',
            name='show_streaming_info',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide Live video url and Live video captions information'),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='live_video_captions',
            field=models.URLField(blank=True, help_text='Leave this field blank to use the default url'),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='live_video_url',
            field=models.URLField(blank=True, default=home.models.MeetingPage.live_video_url, help_text='https://fec.adobeconnect.com/openmeeting/', null=True),
        ),
    ]
