# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0101_auto_20180125_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertForEmergencyUseOnly',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('alert_description', models.CharField(blank=True, max_length=255)),
                ('alert_link_title', models.CharField(blank=True, max_length=255)),
                ('alert_link_url', models.URLField(blank=True, max_length=255)),
                ('alert_date_active', models.DateTimeField(help_text='Set active date-active here and         leave Go-Live and Expiry fields blank in the Settings-Tab above')),
                ('alert_date_inactive', models.DateTimeField(help_text='Set date-inactive here and         leave Go-Live and Expiry fields blank in the Settings-Tab above', null=True)),
                ('alert_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepagebanneralert',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepagebannerannouncement',
            name='date_active',
            field=models.DateTimeField(help_text='Set active date-active here and         leave Go-Live and Expiry fields blank in the Settings-Tab above'),
        ),
        migrations.AlterField(
            model_name='homepagebannerannouncement',
            name='date_inactive',
            field=models.DateTimeField(help_text='Set date-inactive here and         leave Go-Live and Expiry fields blank in the Settings-Tab above', null=True),
        ),
        migrations.DeleteModel(
            name='HomePageBannerAlert',
        ),
    ]
