# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-31 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20180530_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='help_with_sections',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='services',
            field=wagtail.wagtailcore.fields.StreamField((('services', wagtail.wagtailcore.blocks.RichTextBlock()),), default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='services_title',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
