# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import home.blocks
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20180718_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='related_topics',
            field=wagtail.fields.StreamField((('related_topics', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(label='Related topic'))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='reporting_examples',
            field=wagtail.fields.StreamField((('reporting_examples', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description')))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='body',
            field=wagtail.fields.StreamField((('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('html', wagtail.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('example_paragraph', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('paragraph', wagtail.blocks.RichTextBlock(required=True))))), ('example_forms', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('forms', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock()), ('media_type', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock())))))))), ('reporting_example_cards', wagtail.blocks.StructBlock((('card_width', wagtail.blocks.ChoiceBlock(choices=[(2, '1/2'), (3, '1/3')], help_text='Control the width of the cards')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(), icon='doc-empty'))))), ('contact_info', wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('item_label', wagtail.blocks.CharBlock(required=False)), ('item_icon', wagtail.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail'), ('github', 'Github'), ('question-bubble', 'Question')])), ('item_info', wagtail.blocks.RichTextBlock(required=True))))))))), ('internal_button', wagtail.blocks.StructBlock((('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())))), ('external_button', wagtail.blocks.StructBlock((('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())))), ('contribution_limits_table', wagtail.snippets.blocks.SnippetChooserBlock('home.EmbedTableSnippet', icon='table', template='blocks/embed-table.html')))),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='citations',
            field=wagtail.fields.StreamField((('citations', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description')))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='continue_learning',
            field=wagtail.fields.StreamField((('continue_learning', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock()), ('media_type', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock()))), icon='doc-empty')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='date',
            field=models.DateField(verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='record_articles',
            field=wagtail.fields.StreamField((('record_articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(target_model=['home.RecordPage']))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='additional_information',
            field=models.TextField(blank=True, help_text='This field        accepts html'),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='agenda',
            field=wagtail.fields.StreamField((('agenda_item', wagtail.blocks.StructBlock((('item_title', wagtail.blocks.TextBlock()), ('item_text', wagtail.blocks.RichTextBlock(required=False)), ('item_audio', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('item_video', wagtail.blocks.URLBlock(help_text='Add a Youtube URL to a specific                time in a video for this agenda item', required=False))))),)),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='live_video_embed',
            field=models.CharField(blank=True, help_text='Youtube video ID of the live-stream of the meeting', max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='time',
            field=models.TimeField(blank=True, help_text='If no time is entered,     the time will be set to 10 a.m.', null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='citations',
            field=wagtail.fields.StreamField((('citations', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description')))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='intro',
            field=wagtail.fields.StreamField((('paragraph', wagtail.blocks.RichTextBlock()),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='related_topics',
            field=wagtail.fields.StreamField((('related_topics', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(label='Related topic'))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='sections',
            field=wagtail.fields.StreamField((('sections', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(required=True)), ('hide_title', wagtail.blocks.BooleanBlock(help_text='Should the section title be displayed?', required=False)), ('content', wagtail.blocks.StreamBlock((('text', wagtail.blocks.RichTextBlock(blank=False, icon='pilcrow', null=False, required=False)), ('documents', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock()), ('media_type', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock()))), icon='doc-empty', template='blocks/section-documents.html')), ('contact_info', wagtail.blocks.StructBlock((('label', wagtail.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('item_label', wagtail.blocks.CharBlock(required=False)), ('item_icon', wagtail.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail'), ('github', 'Github'), ('question-bubble', 'Question')])), ('item_info', wagtail.blocks.RichTextBlock(required=True))))))))), ('internal_button', wagtail.blocks.StructBlock((('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())))), ('external_button', wagtail.blocks.StructBlock((('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())))), ('page', wagtail.blocks.PageChooserBlock(template='blocks/page-links.html')), ('disabled_page', wagtail.blocks.CharBlock(blank=False, help_text='Name of a disabled link', icon='placeholder', null=False, required=False, template='blocks/disabled-page-links.html')), ('document_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()))), icon='doc-empty', template='blocks/document-list.html')), ('current_commissioners', home.blocks.CurrentCommissionersBlock()), ('fec_jobs', home.blocks.CareersBlock()), ('mur_search', home.blocks.MURSearchBlock()), ('audit_search', home.blocks.AuditSearchBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('html', wagtail.blocks.RawHTMLBlock()), ('reporting_example_cards', wagtail.blocks.StructBlock((('card_width', wagtail.blocks.ChoiceBlock(choices=[(2, '1/2'), (3, '1/3')], help_text='Control the width of the cards')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(), icon='doc-empty'))))), ('contribution_limits_table', wagtail.snippets.blocks.SnippetChooserBlock('home.EmbedTableSnippet', icon='table', template='blocks/embed-table.html'))))), ('aside', wagtail.blocks.StreamBlock((('title', wagtail.blocks.CharBlock(icon='title', required=False)), ('document', wagtail.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock()), ('media_type', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock())))), ('link', wagtail.blocks.StructBlock((('link_type', wagtail.blocks.ChoiceBlock(choices=[('calculator', 'Calculator'), ('calendar', 'Calendar'), ('record', 'Record'), ('search', 'Search')], help_text='Set an icon', icon='link', required=False)), ('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock(required=True)), ('coming_soon', wagtail.blocks.BooleanBlock(required=False)))))), icon='placeholder', required=False, template='blocks/section-aside.html'))))), ('image', wagtail.images.blocks.ImageChooserBlock())), blank=True, null=True),
        ),
    ]
