# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_auto_20191003_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportingExamplePage',
            new_name='ExamplePage',
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('example_image', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.RichTextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('reporting_example_cards', wagtail.blocks.StructBlock([('card_width', wagtail.blocks.ChoiceBlock(choices=[(2, '1/2'), (3, '1/3')], help_text='Control the width of the cards')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(), icon='doc-empty'))])), ('internal_button', wagtail.blocks.StructBlock([('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())])), ('external_button', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.blocks.RawHTMLBlock())], null=True),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='pre_title',
            field=models.CharField(blank=True, choices=[('how', 'How to report'), ('scenario', 'Example scenario'), ('example', 'Example')], max_length=255, null=True),
        ),
    ]
