# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('home', '0106_examplepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplepage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='examplepage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='reportingexamplepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('example_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.RichTextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('reporting_example_cards', wagtail.core.blocks.StructBlock([('card_width', wagtail.core.blocks.ChoiceBlock(choices=[(2, '1/2'), (3, '1/3')], help_text='Control the width of the cards')), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(), icon='doc-empty'))])), ('internal_button', wagtail.core.blocks.StructBlock([('internal_page', wagtail.core.blocks.PageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())])), ('external_button', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('text', wagtail.core.blocks.CharBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AlterField(
            model_name='reportingexamplepage',
            name='pre_title',
            field=models.CharField(blank=True, choices=[('how', 'How to report'), ('scenario', 'Example scenario'), ('example', 'Example')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ExamplePage',
        ),
    ]
