# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 02:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_auto_20191213_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullwidthpage',
            name='citations',
            field=wagtail.fields.StreamField([('citations', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description'))])))], blank=True, null=True),
        ),
    ]
