# Generated by Django 3.1.14 on 2022-03-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_auto_20220303_1357'),
        ('home', '0122_auto_20220302_2114'),
    ]

    operations = [
    ]
