# Generated by Django 3.2.16 on 2023-03-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_auto_20220706_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedsnippet',
            options={'ordering': ['-id']},
        ),
    ]
