# Generated by Django 3.2.16 on 2023-03-07 04:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0124_auto_20220706_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingDatesTables',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('states', wagtail.fields.StreamField([('state', wagtail.blocks.StructBlock([('state_name', wagtail.blocks.CharBlock(form_classname='', icon='')), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'renderer': 'html'}))]))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
