# Generated by Django 3.2.16 on 2023-03-08 05:18

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_reportingdatestables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdatestables',
            name='states',
            field=wagtail.fields.StreamField([('state', wagtail.blocks.StructBlock([('state_name', wagtail.blocks.CharBlock(Required=False, blank=True, form_classname='', icon='')), ('state_table', wagtail.contrib.table_block.blocks.TableBlock(blank=True, table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}, template='blocks/reporting-dates-table-block.html'))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
