# Generated by Django 3.2.16 on 2023-04-20 16:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0125_officepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingDatesTable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('reporting_dates_table', wagtail.fields.StreamField([('dates_table', wagtail.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(help_text='<table class="htcore handsontable" style="table-layout:fixed;width: calc(100% - 294px);position: fixed;top: 20%;">                        <tr><td>State</td><td>Election date</td><td>Close of books+</td><td>Mailing deadline++</td>                        <td>Filing deadline++</td><td>48-Hour Notices**</td></tr</table>', table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}))], blank=True, form_classname='title'))], blank=True, null=True, use_json_field=True)),
                ('footnotes', wagtail.fields.StreamField([('footnote_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank='true', help_text='either &quot;Footnotes&quot; or &quot;Header notes&quot;', icon='title')), ('footnote', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('footnote_number', wagtail.blocks.CharBlock(blank='true', form_classname='title', icon='tag')), ('footnote_text', wagtail.blocks.RichTextBlock(blank='true', help_text='', icon='pilcrow'))])))], blank=True))], blank=True, use_json_field=True)),
                ('citations', wagtail.fields.StreamField([('citations', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description'))])))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
