# Generated by Django 3.2.16 on 2023-02-27 05:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_officepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officepage',
            name='offices',
            field=wagtail.fields.StreamField([('office_title', wagtail.blocks.CharBlock()), ('office_description', wagtail.blocks.RichTextBlock(blank=True)), ('contact_info', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(icon='title', required=False)), ('contact_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('item_label', wagtail.blocks.CharBlock(required=False)), ('item_icon', wagtail.blocks.ChoiceBlock(choices=[('email', 'Email'), ('fax', 'Fax'), ('hand', 'Hand delivery'), ('phone', 'Phone'), ('mail', 'Mail'), ('github', 'Github'), ('question-bubble', 'Question')])), ('item_info', wagtail.blocks.RichTextBlock(required=True))])))], icon='', template='')), ('employee', wagtail.blocks.StructBlock([('employee_name', wagtail.blocks.CharBlock(blank=True)), ('employee_title', wagtail.blocks.CharBlock(blank=True)), ('employee_image', wagtail.images.blocks.ImageChooserBlock(blank=True)), ('employee_bio', wagtail.blocks.RichTextBlock(blank=True))])), ('sub_offices', wagtail.blocks.RichTextBlock(blank=True))], blank=True, null=True, use_json_field=True),
        ),
    ]
