# Generated by Django 3.2.18 on 2023-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_officepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='show_contact_app',
            field=models.BooleanField(default=False, help_text='True: the main column should be the snippet and the contact/help app.\n        False: the main column will be the fields after this one.'),
        ),
    ]
