# Generated by Django 3.2.18 on 2023-05-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_officepage'),
        ('home', '0127_auto_20230123_1927'),
    ]

    operations = [
    ]
