# Generated by Django 3.2.16 on 2023-03-09 22:55

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0127_alter_reportingdatestables_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdatestables',
            name='states',
            field=wagtail.fields.StreamField([('state', wagtail.blocks.StructBlock([('state_table', wagtail.blocks.StructBlock([('state_names', wagtail.blocks.CharBlock(blank=True)), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}))], blank=True, form_classname='title'))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
