# Generated by Django 3.2.19 on 2023-06-30 02:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0128_merge_0125_officepage_0126_auto_20230123_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingDatesTable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('reporting_dates_table', wagtail.fields.StreamField([('dates_table', wagtail.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}))], blank=True, form_classname='title'))], blank=True, null=True, use_json_field=True)),
                ('footnotes', wagtail.fields.StreamField([('footnote_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank='true', help_text='either &quot;Footnotes&quot; or &quot;Header notes&quot;', icon='title')), ('footnote', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('footnote_number', wagtail.blocks.CharBlock(blank='true', form_classname='title', icon='tag')), ('footnote_text', wagtail.blocks.RichTextBlock(blank='true', help_text='', icon='pilcrow'))])))], blank=True))], blank=True, use_json_field=True)),
                ('citations', wagtail.fields.StreamField([('citations', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock(help_text='Use Shift + Enter to add line breaks between citation and description'))])))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
