# Generated by Django 3.2.19 on 2023-07-13 18:00

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_reportingdatestable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdatestable',
            name='reporting_dates_table',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(blank=True)), ('html', wagtail.blocks.RawHTMLBlock()), ('internal_button', wagtail.blocks.StructBlock([('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())])), ('external_button', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())])), ('dates_table', wagtail.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}))], blank=True, form_classname='title', required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
