# Generated by Django 3.2.19 on 2023-07-11 15:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_reportingdatestable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdatestable',
            name='footnotes',
            field=wagtail.fields.StreamField([('footnote_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.ChoiceBlock(Null=True, blank=True, choices=[('Footnotes', 'Footnotes'), ('Header notes', 'Header notes')], help_text='Choose either Footnotes or Header notes')), ('footnote', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('footnote_number', wagtail.blocks.CharBlock(blank='true', form_classname='title', icon='tag')), ('footnote_text', wagtail.blocks.RichTextBlock(blank='true', help_text='', icon='pilcrow'))])))], blank=True))], blank=True, use_json_field=True),
        ),
    ]
