# Generated by Django 4.2.10 on 2024-02-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('home', '0132_auto_20231130_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(app_label)s_%(class)s_items',
                                    to='taggit.tag'),
        ),
    ]
