# Generated by Django 4.2.10 on 2024-04-25 05:02

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_alter_recordpagetag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedsnippet',
            name='banner_icon',
            field=models.TextField(blank=True, default='info', help_text="This field applies to informational-message snippets only. Input 'info' or 'alert'. Default is 'info'"),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('informational_message', wagtail.snippets.blocks.SnippetChooserBlock('home.EmbedSnippet', help_text='Use for an info or alert message banner', icon='warning', template='blocks/embed-info-message.html'))], blank=True, null=True, use_json_field=True),
        ),
    ]
