# Generated by Django 4.2.10 on 2024-09-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0136_alter_embedsnippet_banner_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionerpage',
            name='picture_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
