# Generated by Django 4.2.17 on 2025-01-10 19:59

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0137_commissionerpage_picture_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdatestable',
            name='reporting_dates_table',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(blank=True)), ('html', wagtail.blocks.RawHTMLBlock()), ('internal_button', wagtail.blocks.StructBlock([('internal_page', wagtail.blocks.PageChooserBlock()), ('text', wagtail.blocks.CharBlock())])), ('external_button', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('text', wagtail.blocks.CharBlock())])), ('dates_table', wagtail.blocks.StructBlock([('hide_state_dropdown', wagtail.blocks.BooleanBlock(help_text='Hide state dropdown on this table?', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': False, 'height': 108, 'language': 'en', 'renderAllRows': True, 'renderer': 'html', 'rowHeaders': False, 'startCols': 6, 'startRows': 1}))], blank=True, form_classname='title', required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
