# Generated by Django 4.2.10 on 2025-01-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0138_alter_reportingdatestable_reporting_dates_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionerpage',
            name='commissioner_bluesky',
            field=models.CharField(blank=True, help_text='The part after https://bsky.app/profile/', max_length=255,
                                   null=True, verbose_name='Commissioner Bluesky handle'),
        ),
        migrations.AlterField(
            model_name='commissionerpage',
            name='commissioner_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Commissioner email address'),
        ),
        migrations.AlterField(
            model_name='commissionerpage',
            name='commissioner_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commissioner phone number'),
        ),
        migrations.AlterField(
            model_name='commissionerpage',
            name='commissioner_twitter',
            field=models.CharField(blank=True, help_text='The part after https://x.com/', max_length=255, null=True,
                                   verbose_name='Commissioner X/Twitter handle'),
        ),
    ]
