# Generated by Django 5.1.9 on 2025-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0139_commissionerpage_commissioner_bluesky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedsnippet',
            name='banner_icon',
            field=models.TextField(blank=True, default='info', help_text='This field applies to informational-message snippets only.             Input `info` or `alert`. Default is `info`'),
        ),
        migrations.AlterField(
            model_name='meetingpage',
            name='additional_information',
            field=models.TextField(blank=True, help_text='This field accepts html'),
        ),
    ]
