# Generated by Django 5.1.9 on 2025-07-15 20:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_courtcaseindexpage_courtcasepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcasepage',
            name='opinions',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
