# Generated by Django 5.1.10 on 2025-08-19 18:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_fectimelinepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FecTimelineItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('entry_date', models.DateField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('order_tiebreaker', models.IntegerField(blank=True, default=0, null=True)),
                ('start_open', models.BooleanField(default=False)),
                ('categories', wagtail.fields.StreamField([('category_selections', 0)], blank=True, block_lookup={0: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('commission', 'Commission'), ('disclosure', 'Disclosure'), ('enforcement', 'Enforcement'), ('legislation', 'Legislation'), ('litigation', 'Litigation'), ('outreach', 'Outreach'), ('public_funding', 'Public funding'), ('regulations', 'Regulations')], 'required': False})}, null=True)),
            ],
            options={
                'verbose_name': 'FEC historical timeline entry',
                'verbose_name_plural': 'FEC historical timeline entries',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='fectimelinepage',
            options={'verbose_name': 'FEC historical timeline page'},
        ),
        migrations.AlterModelOptions(
            name='oiglandingpage',
            options={'verbose_name': 'OIG landing page'},
        ),
        migrations.RemoveField(
            model_name='fectimelinepage',
            name='timeline_entries',
        ),
    ]
