# Generated by Django 5.1.14 on 2025-12-08 17:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_fectimelinepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fectimelinepage',
            options={'verbose_name': 'FEC historical timeline page'},
        ),
        migrations.AlterModelOptions(
            name='oiglandingpage',
            options={'verbose_name': 'OIG landing page'},
        ),
        migrations.AlterField(
            model_name='fectimelinepage',
            name='timeline_entries',
            field=wagtail.fields.StreamField([('year', 8)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'disable_comments': True, 'max_value': 2050, 'min_value': 1960}), 1: ('wagtail.blocks.DateBlock', (), {'disable_comments': True, 'format': '%Y-%m-%d'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'form_classname': 'timeline-summary', 'label': 'Summary'}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Content'}), 4: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('commission', 'Commission'), ('disclosure', 'Disclosure'), ('enforcement', 'Enforcement'), ('legislation', 'Legislation'), ('litigation', 'Litigation'), ('outreach', 'Outreach'), ('public_funding', 'Public funding'), ('regulations', 'Regulations')], 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'disable_comments': True, 'form_classname': 'single-line-checkbox', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('entry_date', 1), ('summary', 2), ('content', 3), ('categories', 4), ('start_open', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('entry', 6)]], {'collapsed': True}), 8: ('wagtail.blocks.StructBlock', [[('year_number', 0), ('entries', 7)]], {})}, null=True),  # noqa: E501
        ),
    ]
