# Generated by Django 5.1.14 on 2025-12-15 15:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_courtcasepage_courtcaseindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcasepage',
            name='see_also_cases',
            field=wagtail.fields.StreamField([('case', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Related court case', 'page_type': ['home.CourtCasePage']})}, help_text='Link to related court cases that should be referenced on the index page', null=True),  # noqa: E501
        ),
    ]
