# Generated by Django 5.1.14 on 2026-01-06 21:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0145_courtcasepage_case_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtcasepage',
            name='summary',
        ),
        migrations.AlterField(
            model_name='courtcasepage',
            name='case_numbers',
            field=wagtail.fields.StreamField([('case_number', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., 06-1247', 'label': 'Case number'})}, help_text='Add one or more case numbers associated with this court case', null=True),  # noqa: E501
        ),
    ]
