# Generated by Django 5.1.12 on 2026-01-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0142_fectimelineitem_alter_fectimelinepage_options_and_more'),
        ('home', '0146_remove_courtcasepage_summary'),
    ]

    operations = [
    ]
