# Generated by Django 5.1.15 on 2026-02-18 19:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0148_alter_courtcasepage_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcaseindexpage',
            name='cross_references',
            field=wagtail.fields.StreamField([('cross_reference', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Plain-text title for the index (e.g., "Americans for Change: FEC v.")', 'label': 'Title'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.CourtCasePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {'help_text': 'Court case pages to link in the "See:" line', 'label': 'See also cases'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('see_also_cases', 2)]], {})}, help_text='Cross-reference entries that appear as plain text with "See:" links', null=True),
        ),
    ]
